# Generated by Django 5.1.5 on 2025-01-22 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpassworduser',
            name='email',
            field=models.EmailField(max_length=120, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(120)]),
        ),
    ]
