# Generated by Django 5.1.5 on 2025-01-20 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='business.business'),
        ),
        migrations.AddField(
            model_name='comment',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='business.promocode'),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='business.promocode'),
        ),
        migrations.AddField(
            model_name='promocodeaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='promocodeactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_activated', to='user.user'),
        ),
        migrations.AddField(
            model_name='promocodecommoninstance',
            name='promocode_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_code', to='business.promocode'),
        ),
        migrations.AddField(
            model_name='promocodeuniqueinstance',
            name='promocode_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_codes', to='business.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.target'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeaction',
            unique_together={('promocode', 'user')},
        ),
        migrations.CreateModel(
            name='PromocodeCommonActivation',
            fields=[
                ('promocodeactivation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.promocodeactivation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promocode_instanse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_activations', to='business.promocodecommoninstance')),
            ],
            bases=('business.promocodeactivation',),
        ),
        migrations.CreateModel(
            name='PromocodeUniqueActivation',
            fields=[
                ('promocodeactivation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.promocodeactivation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promocode_instanse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_activations', to='business.promocodeuniqueinstance')),
            ],
            bases=('business.promocodeactivation',),
        ),
    ]
