# Generated by Django 5.1.5 on 2025-01-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_promocode_uuid'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.promocode')),
            ],
            options={
                'unique_together': {('promocode', 'profile')},
            },
        ),
    ]
