# Generated by Django 5.1.5 on 2025-01-20 13:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='common_activations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='unique_activation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)]), blank=True, max_length=20, null=True, size=None),
        ),
    ]
