# Generated by Django 5.1.5 on 2025-01-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_promocode_common_activations_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='unique_activation_count',
            new_name='unique_activations_count',
        ),
    ]
