# Generated by Django 5.1.5 on 2025-01-19 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_promocodeaction'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='business.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
