# Generated by Django 5.1.5 on 2025-01-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodeaction',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='business.promocode'),
        ),
    ]
