# Generated by Django 5.1.5 on 2025-01-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_rename_unique_activation_count_promocode_unique_activations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.target'),
        ),
    ]
