# Generated by Django 5.1.5 on 2025-01-20 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_promocode_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodeuniqueinstance',
            name='promocode',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
