# Generated by Django 5.1.5 on 2025-01-24 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_promocodeuniqueinstance_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='image_url',
            field=models.URLField(blank=True, max_length=350, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(350)]),
        ),
    ]
